version: '3.8'

services:
  web:
    build: web
    ports:
      - "8081:8080"
    networks:
      - app42_net

  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: app42
      MYSQL_USER: app42admin
      MYSQL_PASSWORD: gahTho7e
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
    networks:
      - app42_net

networks:
  app42_net: